<a href="https://colab.research.google.com/github/PratikSavla/Reinformemt-Learning-Examples/blob/master/Q_learning_frozen_lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
!pip install gym

In [0]:
#Frozen lake from open ai gym

In [0]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [0]:
env = gym.make("FrozenLake-v0")

In [39]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [41]:
rewards_all_episodes = []

#Q-Learning
for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        q_table[state, action] = q_table[state, action]*(1-learning_rate) + learning_rate*(reward + discount_rate*np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            break

    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)

rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("Avg reward per 1000 episodes")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

print("Q-table")
print(q_table)









Avg reward per 1000 episodes
1000 :  0.06900000000000005
2000 :  0.20500000000000015
3000 :  0.4150000000000003
4000 :  0.5590000000000004
5000 :  0.6490000000000005
6000 :  0.6460000000000005
7000 :  0.6780000000000005
8000 :  0.6710000000000005
9000 :  0.7000000000000005
10000 :  0.6830000000000005
Q-table
[[0.58539918 0.51288722 0.53292661 0.5043818 ]
 [0.30599389 0.3788993  0.31501549 0.51390088]
 [0.41525086 0.42434784 0.3920751  0.4845103 ]
 [0.2933425  0.31175949 0.31441842 0.4523224 ]
 [0.6118956  0.3934067  0.41405617 0.44282812]
 [0.         0.         0.         0.        ]
 [0.12303995 0.17643558 0.48157172 0.04658266]
 [0.         0.         0.         0.        ]
 [0.39544917 0.42886378 0.30799949 0.65860096]
 [0.27360986 0.72518675 0.58007262 0.43024249]
 [0.66345475 0.3569864  0.28780194 0.2853154 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.57118917 0.57469386 0.82365982 0.39290325]
 [0.72013901 0.90940379 0.763747

In [42]:
for episode in range(3):
    state = env.reset()
    print("Episode ", episode+1)
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward ==1:
                print("You reached goal")
                time.sleep(3)
            else:
                print("You fall through hole")
                time.sleep(3)
            clear_output(wait=True)
            break
        state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
You reached goal
